services:
  - type: web
    name: ai-weather-app
    env: python
    plan: starter   # or "free" for free tier
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: WEATHER_API_KEY
        fromEnvVar: WEATHER_API_KEY
      - key: GEMINI_API_KEY
        fromEnvVar: GEMINI_API_KEY
